# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-23 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date', 'title'], 'verbose_name': 'notices'},
        ),
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(related_name='notices', to='catalogue.Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='books',
            field=models.ManyToManyField(related_name='notices', to='catalogue.Book'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='notices', to='catalogue.Tag'),
        ),
    ]
