# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-23 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63, verbose_name='first name')),
                ('last_name', models.CharField(max_length=63, verbose_name='last name')),
                ('birth_date', models.DateField(verbose_name='date of birth')),
                ('slug', models.SlugField(help_text='A unique label for URL config.', max_length=127, unique=True)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023)),
                ('slug', models.SlugField(help_text='A unique label for URL config.', max_length=1023, unique=True)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('publisher', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('location', models.CharField(max_length=1023)),
                ('status', models.CharField(max_length=63)),
                ('authors', models.ManyToManyField(related_name='books', to='catalogue.Author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(help_text='A unique label for URL config.', max_length=31, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='books', to='catalogue.Tag'),
        ),
    ]
